#spring.jpa.show-sql = true
#spring.datasource.url=jdbc:mysql://localhost:3306/app_twendee?UseSSL=false;
#spring.datasource.username=root
#spring.datasource.password=root
#  #spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.hibernate.ddl-auto=update
##spring.datasource.driverClassName=com.mysql.jdbc.Driver

spring:
  jackson:
    date-format: dd/MM/yyyy
    time-zone: Asia/Saigon
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/app_twendee?UseSSL=false;
    username: root
    password: root

#spring.jackson.date-format=dd/MM/yyyy
#  spring.jackson.time-zone=Asia/Saigon
