spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/app?serverTimezone=UTC
    username: root
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace